version: 0.0

os: linux

files:
  - source:  / # 현재 프로젝트의 루트 경로
    destination: /home/ec2-user/app/nonstop/mukcha/  # EC2 내부 배포 할 위치
    overwrite: yes # 덮어쓰기

hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: execute-deploy.sh
      timeout: 60

# permissions:
#   - object: /
#     pattern: "**"
#     owner: ec2-user
#     group: ec2-user

# hooks:
#   AfterInstall: # 배포가 끝나면
#     - location: stop.sh # stop.sh 스크립트 파일을 실행시켜서 실행 중이던 스프링 부트 jar를 종료
#       timeout: 60
#       runas: root

#   ApplicationStart: # 중지된 서비스를 다시 시작
#     - location: start.sh # 배포할 새로운 버전의 jar 파일을 실행
#       timeout: 60
#       runas: root

#   ValidateService: # 배포가 성공적으로 완료되었는지 확인
#     - location: health.sh
#       timeout: 60
#       runas: root