server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # MySQL username과 password로 변경
  datasource:
    username: bluewind
    password: sialn9aldac
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-test.c8odve5cbglu.ap-northeast-2.rds.amazonaws.com:3306/mukcha
    # url: jdbc:mysql://localhost:3306/mukcha?serverTimezone=Asia/Seoul

  jpa:
    open-in-view: false # Explicitly configure spring.jpa.open-in-view to disable this warning
    generate-ddl: false # 구현체와 상관없이 자동화된 ddl 을 설정하는 값
    hibernate:
      ddl-auto: update
    show-sql: true # 콘솔에 jpa 실행쿼리
    properties:
      hibernate:
        format_sql: true # 실행쿼리를 가독성있게 표현

  output:
    ansi:
      enabled: always # console color

  mvc:
    hiddenmethod:
      filter:
        enabled: true # for using PUT, DELETE mapping

# naver oauth2
  security:
    oauth2:
      client:
        # registration
        registration:
          naver:
            client-id: 29ePxl3H1XTUdqOjcD4X
            client-secret: qtu0G6tjle
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}" # (== http://localhost:8080/login/oauth2/code/naver)
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name,email,profile_image
        # provider
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


logging:
  level: 
    org.springframework.web: trace # controller 가 제대로 서버에 뜨고잇는지 로그 확인

