server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mukcha?serverTimezone=Asia/Seoul

  jpa:
    open-in-view: false # Explicitly configure spring.jpa.open-in-view to disable this warning
    generate-ddl: false # 구현체와 상관없이 자동화된 ddl 을 설정하는 값
    hibernate:
      ddl-auto: create
    show-sql: true # 콘솔에 jpa 실행쿼리
    properties:
      hibernate:
        format_sql: true # 실행쿼리를 가독성있게 표현

  output:
    ansi:
      enabled: always # console color


